//
//  ViewController.swift
//  ios101-project6-tumblr
//

import UIKit
import Nuke

struct Internship {
    let title: String
    let description: String
    let imageUrl: String
}

class ViewController: UIViewController, UITableViewDataSource {

    @IBOutlet weak var tableView: UITableView!

    var internships: [Internship] = [
            Internship(title: "STEP (Student Training in Engineering Program)", description: "The internship program has a focus of providing development opportunities to students from groups historically underrepresented in tech, through technical training and professional development. Our unique internship offers the opportunity to work on a software project alongside other STEP interns and full-time Googlers, and provides the chance to bridge the gap between academic understanding and practical professional experience.", imageUrl: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20220720121505/google2.jpg"),
            Internship(title: "The New Technologists", description: "The New Technologists™ (TNT) is an award-winning 7-week innovation academy in partnership with Microsoft for college freshmen and sophomores interested in pursuing a career in tech. The program inspires ideation and introduces various tools/programming languages, provides hands-on training and real-world experience with senior engineers, and teaches the skills necessary to navigate the professional world.", imageUrl: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWCZER?ver=1433&q=90&m=6&h=195&w=348&b=%23FFFFFFFF&l=f&o=t&aim=true"),
            Internship(title: "Breakthrough Collaborative", description: "Breakthrough Collaborative has been creating empowering educational experiences for traditionally underrepresented students on their path to college and operates the largest pre-professional teacher training program in the country. Breakthrough Teaching Fellows play an integral role in Breakthrough’s nationally recognized middle school summer program.", imageUrl: "https://static.wixstatic.com/media/3c017e_c059fdbbdb5b46b0873e0a0f8d67e472~mv2.jpg/v1/fill/w_560,h_322,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/breakthroughcollaborativelogo.jpg"),
            Internship(title: "Code2040", description: "The Fellows Program is an intensive career accelerator for Black and Latinx college and graduate-level computer science students. For 9 weeks between June and August, you’ll intern at a top tech company and engage in racial equity advocacy work. You’ll participate in a series of learning experiences designed to give you the tools and resources you need to navigate the tech industry, build a lasting career, and advocate for yourself and your community.", imageUrl: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1403566678/yybu71kqxebphvljrruo.png"),
            Internship(title: "MLH Fellowship", description: "The MLH Fellowship is a 12-week internship alternative for aspiring technologists. Fellows on the Site Reliability Engineering track experience what it's like to work in Site Reliability Engineering and DevOps.", imageUrl: "https://media.licdn.com/dms/image/C560BAQGig0-5n4XMkA/company-logo_200_200/0/1671221609482/mlh_fellowship_logo?e=2147483647&v=beta&t=dmx6FjmPUBu2mdQD6fSQ39fIam7tAvIo8Yw2WIQkEg4"),
            Internship(title: "Uber STAR", description: "UberSTAR is a paid student internship program designed to promote equal opportunity, inclusion, and access in tech by encouraging applications from women and underrepresented people, including but not limited to Black, Hispanic, Native American, students with disabilities, LGBTQIA+, and Veterans. This program is open to all first or second year students (freshman and sophomores) enrolled full-time in a community college or university, regardless of race, gender, or ethnicity. UberSTAR connects students interested in working in tech with full-time internships at Uber to provide participants with real-work skills, experiences, and the professional networks they need to succeed.", imageUrl: "https://mma.prnewswire.com/media/1763672/Uber_Logo.jpg?p=facebook"),
            Internship(title: "Uber Career Prep", description: "Uber Career Prep brings transparency and raises visibility around the necessary steps to embark on a STEM career to traditionally underrepresented groups in tech. Regardless of your gender, race, religion, abilities, or sexual orientation, we champion your right to learn and succeed without fear.", imageUrl: "https://mma.prnewswire.com/media/1763672/Uber_Logo.jpg?p=facebook"),
            Internship(title: "Ernst & Young", description: " The Launch Internship will serve as a launch pad to your career. We will provide you with the experience, exposure and knowledge needed to better understand who we are and the work we do in professional services so that you can figure out what you want and begin building your unique career.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/EY_logo_2019.svg/1200px-EY_logo_2019.svg.png"),
            Internship(title: "Capital One Analyst Early Internship Program", description: "The Analyst Early Internship Program (AEIP) is an immersive experience that will equip you with valuable knowledge and skills to prepare you for future opportunities as a Business Analyst Capital One. This unique 10-week program will focus on learning and skill-development, and a hands-on project that will give you a chance to show off what you’ve learned alongside our full-time Business Analysts. You will also benefit from opportunities to network and receive mentorship from our top-notch associates, as well as experience a deep dive into our business culture.", imageUrl: "https://www.investopedia.com/thmb/XZMGSsDxZY9FlLQGlGLGTTPXBj4=/fit-in/1500x1000/filters:format(png):fill(white):max_bytes(150000):strip_icc()/Capital-one-c7a42efc1bbb4955a9282ab587ad839d.jpg"),
            Internship(title: "SEO Tech Developer", description: "SEO Tech Developer is a virtual intensive, free immersion program that propels first-year and sophomore computer science and software engineering college students, including those who identify as Black, Latinx, or Native American, to the next level — including a PAID six-week summer residency.", imageUrl: "https://www.seo-usa.org/wp-content/uploads/2021/12/logo-2-300x300.png"),
            Internship(title: "Disney College Program", description: "Ready to go behind the magic with instructor-led offerings or looking for academic support to continue reaching your goals? On the Disney College Program, we have crafted our program-exclusive learning opportunities to give interns the ultimate addition to their academic and professional careers. The internship program is even recommended for college credit by the American Council on Education.", imageUrl: "https://sites.disney.com/app/uploads/sites/57/2023/01/DCP-Logo-Feature-Image.png"),
            Internship(title: "YYGS Instructor", description: "Yale Young Global Scholars (YYGS) hires instructional staff to teach in-person at Yale University. Preferred candidates include graduate or undergraduate students, or recent graduates, with a desire to teach and a passion for working cooperatively with others. Instructional staff mentor and teach students in one or more of our YYGS academic tracks.", imageUrl: "https://mladiinfo.eu/wp-content/uploads/2020/10/343.jpg"),
            Internship(title: "ID Tech Stem Instructor", description: "ID Tech hires the industry's most talented individuals who care deeply about youth STEM education. Each employee leverages their craft to drive organizational success—whether it's delivering engaging curriculum, delighting clients with positively outrageous service, or engineering systems to enable growth. By banding together, each department plays an important role in creating life-changing experiences for the next generation of innovators. And humble brag? iD Tech’s commitment to our people and purpose have led us to earn the Bay Area News Group Top Workplaces Award 10 times!", imageUrl: "https://static.wayup.com/company_logo/hwkimjXuxl_20221108.png"),
            Internship(title: "Lavner Education", description: "Lavner Education, one of the world's leading Edtech companies for kids, powers the Lavner Camps, Tech Revolution, Lavner IQ, and Lavner Fitness brands, offering year-round camps, classes, tournaments, and online tutoring to kids worldwide. Whether at locations like UPenn, NYU, WashU, UW-Seattle, and UCLA, or through online camps and private instruction, our multi-layered approach to education is redefining the industry like never before. By embracing the concept that kids should love what they do and have the opportunity for high-quality live, interactive learning, we create cutting-edge learning experiences that feature top-notch curricula and great staff, all backed by a dedicated and mission-driven leadership team", imageUrl: "https://media.glassdoor.com/sqll/1466525/lavner-camps-squareLogo-1670260024686.png"),
            Internship(title: "Discovery Internship Deloitte", description: "The Discovery Internship is designed to expose freshman and sophomore summer interns different client service businesses at Deloitte. This opportunity will help you grow your skills, empower your curiosity, celebrate your versatility, and discover your impact.", imageUrl: "https://mma.prnewswire.com/media/379251/Deloitte_Logo.jpg?p=twitter"),
            Internship(title: "Girls Who Invest Summer Intensive Program", description: "It is intensive, immersive and an incredible opportunity to explore a career in finance and investment as part of a supportive community of peers, lecturers, industry experts, alumni, and GWI staff.", imageUrl: "https://pbs.twimg.com/profile_images/1027967521469751296/AILUJvEJ_400x400.jpg"),
            Internship(title: "Citi Pre-internship Programs", description: "pre-internship programs have been designed to provide an introduction to opportunities at Citi for students early on in their undergraduate or masters education (where applicable as opportunities may vary by location). These short-term programs may take place over spring break or other various times throughout the year and have been designed to provide education, exposure, experience and mentorship. Successful pre-interns may be offered the opportunity to be assessed for a position for a future analyst program opportunity.", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9vmr_lFgNFHM03jnVcHtBPOJZ9q4hB6gZ9ZlODqE47w&s"),
            Internship(title: "RingCentral", description: "The RingTern Program is a 12-week internship designed to provide valuable real-world experience across a diverse range of disciplines. Available in the United States, United Kingdom, France, Philippines, and China, this program offers internships in various focus areas including marketing, finance, sales, IT, engineering, human resources, and legal, among others. This broad spectrum of departments allows participants to gain comprehensive insights and develop specific skills pertinent to their chosen field in a global context.", imageUrl: "https://www.ringcentral.com/content/dam/rc-www/en_us/images/content/whyringcentral/pressimages/dec-2023/logo-jpg-rendition.webp"),
            Internship(title: "RingCentral Rising Stars Program", description: "The Rising Start Program offers early career opportunities aimed at providing comprehensive mentorship, training, and support to foster future success in various professional fields. Participants in this program can explore career paths in marketing, finance, sales, IT, engineering, HR, legal, and more. The program is designed to equip individuals at the start of their careers with the necessary skills and knowledge to excel in their chosen fields, supported by experienced mentors who guide their professional development.", imageUrl: "https://www.ringcentral.com/content/dam/rc-www/en_us/images/content/whyringcentral/pressimages/dec-2023/logo-jpg-rendition.webp"),
            Internship(title: "Moody's Investor Services: Moody’s Analytics Technology Rotation Program", description: "MATR participants complete four, six-month rotations across two years before receiving a final team placement at the end of the program.  MATR is open to new graduates who have studied Computer Science, Software Engineering or another related field.  MATR participants are passionate about learning and working with any or all the following: Java, .NET, Scala, Apache Spark, Hadoop, AngularJS, React, Python, Amazon Web Services and Microsoft Azure. We begin posting MATR positions in September.", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdtAWHcpCTUX9-Y5r2NDQXdzYZvPxidkd9PgZK6LINUg&s"),
            Internship(title: "Pimco", description: "PIMCO’s internships are meant to offer a realistic professional and meaningful educational experience. Every internship starts with formal training that runs alongside informal experiences in an immersive learning environment. The goal is to offer you the opportunity to leverage your specialty skills, take an active role in the firm and make a positive impact on the business.", imageUrl: "https://cdn.uconnectlabs.com/wp-content/uploads/sites/125/2022/03/pimco-logo-vector.png"),
            Internship(title: "Deepki", description: "6-month customer success internship opportunity in Paris (French proficiency required). Deepki is an ESG software platform for real estate working mostly in the European market and my friend really likes the company.", imageUrl: "https://nla-production-media.s3.eu-west-2.amazonaws.com/51528/Copie-de-Deepki_Logo_Wordmark_Connector_RGB-04.png?v=1691674305"),
            Internship(title: "Starta VC", description: "Accelerator Associate Program. Work with real early stage founders from all over the world, help them launch and scale their startups in US.", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6RqO1_O5Jejl91mutMinakOCbuEdiN5_apj8SIsltng&s"),
            Internship(title: "PRIMO", description: "PRIMO is open to continuing students (those who will be rising sophomores, juniors, or seniors) who are in good standing at a 4-year undergraduate institution in the United States. International students who are enrolled at a US institution are eligible to apply. Upon completion of the program, students return to their home institution to complete their undergraduate degrees. We are unable to sponser participants from institutions outside of the United States, recent graduates, or those with graduate degrees.", imageUrl: "https://media.designrush.com/inspiration_images/131656/conversions/_1523460223_965_Harvard-Wreath-Logo_ab2ece9fbd52-mobile.jpg"),
            Internship(title: "Yale Information Technology Services with a IT Summer College Internship", description: "These paid, full-time, 10- to 12-week positions give you the chance to work side by side with IT professionals on projects matched with your skills and interests. Assignments will give you hands-on experience, exposure to a collaborative culture, and opportunities to sharpen problem-solving and critical-thinking skills. You will acquire professional experience and learn about IT functions throughout the university. In addition, you will develop your career-building skills and increase your knowledge through career-building workshops and networking activities.", imageUrl: "https://i.pinimg.com/736x/20/33/58/203358e5a19d1567ab83bc612ae1a61f.jpg"),
            Internship(title: "World Wide Fund for Nature BRIDGE program", description: "BRIDGE is WWF’s diversity-focused summer internship program, facilitated by the Diversity, Equity, and Inclusion (DEI) team. Launched in 2021, it is a paid internship opportunity aimed at a diverse pool of talented undergraduate and graduate students who could bring fresh thinking and innovation to the environmental sector. In particular, WWF aims to employ interns who have not previously had a breadth of professional experience.", imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/24/WWF_logo.svg/1200px-WWF_logo.svg.png"),
            Internship(title: "Brookings", description: "The Brookings Internship Program is an opportunity for degree-seeking students to engage in career exploration and development, as well as a chance to learn new skills. Its mission is to provide a pre-professional, meaningful and practical work experience related to the student’s field of study or career interest. Internships may be within a Brookings research program (*e.g.,* Governance Studies, Global Economy and Development, Brookings Metro, Economic Studies, or Foreign Policy) or one of Brookings’s central business units (*e.g.,* Human Resources, Executive Office, Finance, Development, Facilities, Communications).", imageUrl: "https://www.brookings.edu/wp-content/uploads/2023/06/brookings-share-default.jpg?quality=75"),
            Internship(title: "Aflac Summer 2024 Internship Program", description: "Aflac is a Fortune 200 company, providing financial protection to more than 50 million people worldwide. When a policyholder or insured gets sick or hurt, Aflac pays cash benefits promptly, for eligible claims, directly to the insured (unless assigned otherwise). For more than six decades, Aflac voluntary insurance policies have given policyholders the opportunity to focus on recovery, not financial stress.", imageUrl: "https://careers.umd.edu/sites/default/files/styles/optimized/public/2024-03/Aflac%20%281%29.png?itok=ISQGFazs"),
            Internship(title: "Galileo Learning", description: "Typically college or high school students, our Summer Operations Interns are the dynamic staff essential to our summer team. These roles are perfect for those who are 16 or older by the start of employment.", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4DtFqivUU8_LlDDIu4TegWwU3QKyJQLQbYuqPM8RdFSypSQ0MXKIjCaEYXXn3Fjd7dno&usqp=CAU"),
            Internship(title: "WRI Ross Center for Sustainable Cities", description: "WRI's Internship Program offers learning experiences designed for current students, recent graduates, or other candidates who wish to gain knowledge about a specific area of work. WRI offers a variety of paid and unpaid internship opportunities throughout the year in offices around the world.", imageUrl: "https://www.wricitiesindia.org/sites/default/files/WRICitiesIndia-RossCenter-logo.png"),
            Internship(title: "Wall Street Oasis", description: "Wall Street Oasis 12-Week Finance Research Analyst Internship", imageUrl: "https://s3-eu-west-1.amazonaws.com/tpd/logos/5a7974d9c1bfc5000110ef62/0x0.png"),
            Internship(title: "Intel Corporation", description: "Bring your analytical thinking skills and a thirst for knowledge. You’ll gain real-time experience modifying, editing, and debugging software products, as well as experience writing, debugging, and profiling source code.", imageUrl: "https://www.thoughtco.com/thmb/xA0zo7FUyCKKiuR39yl56V2y5so=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/intel-logo-56a6fa195f9b58b7d0e5ce3a.png"),
            Internship(title: "Iacocca Global Village", description: "**Iacocca Global Village is an intensive, immersive virtual and in-person program on the campus of Lehigh University that teaches university students and young professionals of all ages entrepreneurship and leadership skills while preparing them to thrive in a global community.", imageUrl: "https://images.squarespace-cdn.com/content/v1/623126b50d2dfb281caaafd3/1651168128562-2AU68ZUQQ80UE6P47NBT/Lehigh-University-logo.jpg?format=750w"),
            Internship(title: "IonQ", description: "Got an in-semester internship opportunity for students interested in quantum computing. Our cloud team at IonQ reached out to me, asking for an intern to work on some backlogged features, primarily concerning the Qiskit SDK. An example of two work tasks in this role is a bugfix in the Qiskit transpiler and work on a hybrid job estimator.", imageUrl: "https://www.hpcwire.com/wp-content/uploads/2021/05/ionq-logo.jpeg"),
        ]

        override func viewDidLoad() {
            super.viewDidLoad()
            tableView.dataSource = self
            tableView.reloadData()
        }

        func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
            return internships.count
        }

        func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
            let cell = tableView.dequeueReusableCell(withIdentifier: "PostCell", for: indexPath) as! PostCell
            let internship = internships[indexPath.row]

            cell.summaryLabel.text = internship.title + " - " + internship.description

            if let url = URL(string: internship.imageUrl) {
                Nuke.loadImage(with: url, into: cell.postImageView)
            }

            return cell
        }
    }
